### ISSUE TITLE
Feature request: Change `$personContext.Person.DisplayName` to correlation value within the logging

### ISSUE THREAD

**Issue by JeroenBL** [Tools4everBV/HelloID-Conn-Prov-Target-V2-Template#18]
### Summary of the new feature / enhancement

As a developer of the connector, I want to see the correlation value instead of the person's display name within the logging because the display name is already visible within HelloID UI. This change will help me to identify and differentiate between users more effectively.

### Current situation
The current codebase uses the `$personContext.Person.DisplayName` within the logging. We would like to have this changed to: `$correlationProperty` and `$correlationValue`.

**Comment by RudolfAmersfoort** [comment]
Resolved in Pull Request https://github.com/Tools4everBV/HelloID-Conn-Prov-Target-V2-Template/pull/22
