### ISSUE TITLE
Feature Request: Explain the purpose of the `Invoke-RestMethod` wrapper function

### ISSUE THREAD

**Issue by JeroenBL** [Tools4everBV/HelloID-Conn-Prov-Target-V2-Template#19]
### Summary of the new feature / enhancement

As a developer of the connector, I want to understand the purpose of the `Invoke-RestMethod` wrapper function through code comments. This will help me grasp its functionality, usage, and benefits.

### Possible comment

```powershell
# The 'Invoke-{ConnectorName}RestMethod' function is a wrapper around the 'Invoke-RestMethod' cmdlet.
# You can use this function when you have to retrieve data using pagination.
# This makes it easier to manage API requests within the connector.
```

**Comment by JeroenBL** [comment]
Since this function is almost never used, it may be better to remove it from the templates and move it to the snippets.

**Comment by RudolfAmersfoort** [comment]
Resolved in Pull Request https://github.com/Tools4everBV/HelloID-Conn-Prov-Target-V2-Template/pull/22

The Invoke Function is moved to: **HelloID-Lib-Prov-HelperFunctions** repo: https://github.com/Tools4everBV/HelloID-Lib-Prov-HelperFunctions/blob/master/PowerShell/Functions/Invoke-ConnectorNameRestMethod.ps1
