### ISSUE TITLE
Feature Request: Clarify `$correlatedAccount = 'userInfo'` assignment

### ISSUE THREAD

**Issue by JeroenBL** [Tools4everBV/HelloID-Conn-Prov-Target-V2-Template#20]
### Summary of the new feature / enhancement

As a developer, I want to understand how to determine if a user must be created or just correlated, with clear comments explaining the purpose and use of the `$correlatedAccount` variable.

**Comment by RudolfAmersfoort** [comment]
Resolved in Pull Request https://github.com/Tools4everBV/HelloID-Conn-Prov-Target-V2-Template/pull/22
